// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlcXFG8Uj-Jd7opkx1tdrjPSS6HXZYpqI',
    appId: '1:60507922701:web:01d66163c6fb2b1cced044',
    messagingSenderId: '60507922701',
    projectId: 'testing-project-8ca1c',
    authDomain: 'testing-project-8ca1c.firebaseapp.com',
    storageBucket: 'testing-project-8ca1c.firebasestorage.app',
    measurementId: 'G-VW0WKNWHE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDfpoPi_jsK3RzgMiYjC5JLfw2aFz8hV0',
    appId: '1:60507922701:android:d621913ba1cda6e4ced044',
    messagingSenderId: '60507922701',
    projectId: 'testing-project-8ca1c',
    storageBucket: 'testing-project-8ca1c.firebasestorage.app',
  );
}
